
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN IDENTIFIER INTEGER LET LPAREN PRINT RPARENprogram : statement_liststatement_list : statement_list statement\n                         | statementstatement : LET IDENTIFIER ASSIGN expressionstatement : PRINT LPAREN expression RPARENexpression : INTEGERexpression : IDENTIFIER'
    
_lr_action_items = {'LET':([0,2,3,6,11,12,13,14,],[4,4,-3,-2,-6,-7,-4,-5,]),'PRINT':([0,2,3,6,11,12,13,14,],[5,5,-3,-2,-6,-7,-4,-5,]),'$end':([1,2,3,6,11,12,13,14,],[0,-1,-3,-2,-6,-7,-4,-5,]),'IDENTIFIER':([4,8,9,],[7,12,12,]),'LPAREN':([5,],[8,]),'ASSIGN':([7,],[9,]),'INTEGER':([8,9,],[11,11,]),'RPAREN':([10,11,12,],[14,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,],[2,]),'statement':([0,2,],[3,6,]),'expression':([8,9,],[10,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','parser.py',72),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','parser.py',77),
  ('statement_list -> statement','statement_list',1,'p_statement_list','parser.py',78),
  ('statement -> LET IDENTIFIER ASSIGN expression','statement',4,'p_statement_let','parser.py',88),
  ('statement -> PRINT LPAREN expression RPAREN','statement',4,'p_statement_print','parser.py',93),
  ('expression -> INTEGER','expression',1,'p_expression_integer','parser.py',98),
  ('expression -> IDENTIFIER','expression',1,'p_expression_variable','parser.py',103),
]
